### ISSUE TITLE
[Feature]: Check whether it is a triangle

### ISSUE THREAD

**Issue by shobhit15082003** [OPCODE-Open-Spring-Fest/shapes#1]
### So, what is it about?

Here you are supposed to create a function with the an appropriate name and appropriate modifiers and you have to take three inputs and then you are supposed to check whether it is possible to make a triangle from those three sides.

Return type : Bool

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by xTwo56** [comment]
Can I have this assignment

**Comment by shobhit15082003** [comment]
## Assigned
Since you asked for some more time so now you are supposed to raise a PR by 11:50  PM of 26.03.24.
