### ISSUE TITLE
[Feature]: Sort in Descending Order

### ISSUE THREAD

**Issue by shobhit15082003** [OPCODE-Open-Spring-Fest/shapes#10]
### So, what is it about?

Here you are supposed to create a function with the an appropriate name and appropriate modifiers and you have to take 5 string inputs in any order and then you have to sort them according to their number of sides in **decreasing order** and them **return the array of strings** which contains the name of the shapes in descending order.

Return type : Array of strings

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by xTwo56** [comment]
@shobhit15082003 Please assign me this issue

**Comment by shobhit15082003** [comment]
## Assigned
You are supposed to raise a PR by 31.03.24
