### ISSUE TITLE
[Feature]: Case Specific

### ISSUE THREAD

**Issue by shobhit15082003** [OPCODE-Open-Spring-Fest/shapes#11]
### So, what is it about?

Create a function which take a single string input and converts all the uppercase characters in it into lower case and then returns the string with lower case and also you are supposed to integrate this function in all the functions and also you are supposed to remove all the modifiers who showing an error whenever an uppercase character was there instead you are supposed to redirect all the strings to this function to convert them to lowercase first.
Example:
Input: TriAngle
 Output: triangle

Input: Triangle
Output: triangle

Return type: String

Note: All easy and medium problems should be encountered first before dealing with this issue.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by xTwo56** [comment]
@shobhit15082003 Please assign me this issue

**Comment by shobhit15082003** [comment]
## Assigned
You are supposed to raise a PR by 31.03.24
