### ISSUE TITLE
[Feature]: Which type of triangle

### ISSUE THREAD

**Issue by shobhit15082003** [OPCODE-Open-Spring-Fest/shapes#4]
### So, what is it about?

Here you are supposed to create a function with the an appropriate name and appropriate modifiers and you have to take three inputs and then you are supposed to check which type of triangle it is i.e. isosceles, scalar or equilateral.

Return type : String

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by xTwo56** [comment]
@shobhit15082003 Kindly assign me this issue

**Comment by shobhit15082003** [comment]
## Assigned
You are supposed to raise a pr till 11:50 AM till 28.03.24
