### ISSUE TITLE
[Feature]: Name of the shape

### ISSUE THREAD

**Issue by shobhit15082003** [OPCODE-Open-Spring-Fest/shapes#5]
### So, what is it about?

Here you are supposed to create a function with the an appropriate name and appropriate modifiers and you have to take one input i.e. of type uint which will the value of the number of sides of that shape and then you are supposed to check which shape has that number of sides.
Example : 
Input : 3
Output: triangle

Return type : String

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by xTwo56** [comment]
@shobhit15082003 kindly assign me this issue

**Comment by shobhit15082003** [comment]
## Assigned
You are supposed to raise a pr till 11:50 AM till 28.03.24
