### ISSUE TITLE
[Feature]: Equal

### ISSUE THREAD

**Issue by shobhit15082003** [OPCODE-Open-Spring-Fest/shapes#6]
### So, what is it about?

Here you are supposed to create a function with the an appropriate name and appropriate modifiers and you have to take 2 inputs one will be of type uint and the other will be of type string and then you are supposed to check whether that shape has the same number of sides as mentioned in the uint input.
Example : 
Input: 3,triangle
Output:true

Return type : Bool

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by xTwo56** [comment]
@shobhit15082003 kindly assign me this issue
