### ISSUE TITLE
[Feature]: Interior angle

### ISSUE THREAD

**Issue by shobhit15082003** [OPCODE-Open-Spring-Fest/shapes#7]
### So, what is it about?

Here you are supposed to create a function with the an appropriate name and appropriate modifiers and you have to take 1 inputs of type uint which represents the number of sides of that shape and then you are supposed to print the value of the interior angle of that shape.
Example :
Input: 8
Output:135

Return type : uint

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by xTwo56** [comment]
@shobhit15082003 kindly assign me this issue

**Comment by shobhit15082003** [comment]
## Assigned
You are supposed to raise a PR by 11:50AM 28.03.24.
