### ISSUE TITLE
[Feature]: Area of 2D

### ISSUE THREAD

**Issue by shobhit15082003** [OPCODE-Open-Spring-Fest/shapes#8]
### So, what is it about?

Here you are supposed to create **3 functions** with the an appropriate name and appropriate modifiers and you have to take inputs accordingly i.e 2 for triangle(consider right angles triangle) of type uint ,3 for rectangle of type uint and 1 for square of type uint which represents the value of the sides of that shape and then you are supposed to print the area of that shape.

Return type : double/float

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by xTwo56** [comment]
@shobhit15082003 Please assign me this issue

**Comment by shobhit15082003** [comment]
## Assigned
You are supposed to raise a PR by 31.03.24
