### ISSUE TITLE
[Feature]: Area of 3D

### ISSUE THREAD

**Issue by shobhit15082003** [OPCODE-Open-Spring-Fest/shapes#9]
### So, what is it about?

Here you are supposed to create 2 functions with the an appropriate name and appropriate modifiers and you have to take inputs accordingly, here you are supposed to return the surface area and volume of Cube and Cuboid .

Return type : Surface area(double/float),Volume(double/float)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by xTwo56** [comment]
@shobhit15082003 Please assign me this issue

**Comment by shobhit15082003** [comment]
## Assigned
You are supposed to raise a PR by 31.03.24
